### ISSUE TITLE
Formating is wrong for 

### ISSUE THREAD

**Issue by bjartek** [Cian911/vim-cadence#2]
If i format with `gg=G` then the following code block will be formated wrong

``` 
pub resource interface INFT {
     // The unique ID that each NFT has
    pub let id: UInt64
    pub fun getName(): String
    pub fun getSchemas() : [String]
    pub fun resolveSchema(_ schema:String): AnyStruct

}
```

```
   // Interface that the NFTs have to conform to
    //
    pub resource interface INFT {
        // The unique ID that each NFT has
        pub let id: UInt64
            pub fun getName(): String
                               pub fun getSchemas() : [String]
                                                       pub fun resolveSchema(_ schema:String): AnyStruct
                                                                           
    }
```

So it looks like the syntax file does not recognize that it is a valid expression. I am not familiar enough with vims syntax files to fix this. But I hope you can. 

Btw i LOVE this little plugin :)

i use it with coc and the cadence lsp and I can finally have cadence code in vim.

**Comment by Cian911** [comment]
@bjartek Thanks for letting me know, and thanks for creating the first issue! 

Appreciate the feedback and support also, I will take a look into it :)

**Comment by bjartek** [comment]
If you are in the discrod for flow send me a ping :)

**Comment by Cian911** [comment]
@bjartek Hey there - I'm finding it hard to replicate your issue. I noticed you have your `.vimrc` referenced under your dotfiles repo. Would you mind updating it so as I can better replicate the issue?

I've also sent you a message on discord
